project:
  type: website

website:
  title: "we could go anywhere"
  image: "Images/Logo.png"
  favicon: "Images/Icon.png"
  page-navigation: true
  navbar:
    logo: "Images/logo.png"
    title: false
    collapse-below: lg
    search: true
    left: 
      - text: "Hands-on Exercises"
        menu: 
          - text: 1a Geospatial Data Wrangling
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html
          - text: 1b Choropleth Mapping
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html            
          - text: 2a 1st Order Spatial Point Patterns Analysis Methods
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html
          - text: 2b 2nd Order Spatial Point Patterns Analysis Methods
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html            
          - text: 3 Network Constrained Spatial Point Patterns Analysis
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html            
          - text: 4 Spatial Weights and Applications
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html
          - text: 5a Global Measures of Spatial Autocorrelation
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html
          - text: 5b Lobal Measures of Spatial Autocorrelation
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html            
          - text: 6 Geographical Segmentation with Spatially Constrained Clustering Techniques
            href: Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html
          - text: 7 Calibrating Hedonic Pricing Model
            href: Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html   
          - text: 8 Geographically Weighted Predictive Models
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html 
          - text: 9a Processing and Visualising Flow Data
            href: Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09a.html 
          - text: 9b Calibrating Spatial Interaction Models
            href: Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09b.html            
          - text: 10 Modelling Geographical Accessibility
            href: Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html 
            
      - text: "In-class Exercises"
        menu: 
          - text: 1 Geospatial Data Science with R
            href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
          - text: 2 Importing Data for Thailand Road Accident Case Study
            href: In-class_Ex/In-class_Ex02/In-class_Ex02.html  
          - text: 3/
            href: In-class_Ex/In-class_Ex03/In-class_Ex03.html    
          - text: 4/
            href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
          - text: 5/
            href: In-class_Ex/In-class_Ex05/In-class_Ex05.html 
          - text: 6/
            href: In-class_Ex/In-class_Ex06/In-class_Ex06.html  
          - text: 7/
            href: In-class_Ex/In-class_Ex07/In-class_Ex07.html              
          - text: 8/
            href: In-class_Ex/In-class_Ex08/In-class_Ex08.html  
          - text: 9/
            href: In-class_Ex/In-class_Ex09/In-class_Ex09.html  
          - text: 10/
            href: In-class_Ex/In-class_Ex10/In-class_Ex10.html  
            
      - text: "Take-home Exercises"
        menu: 
          - text: 1/
            href: Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html    
          - text: 2/
            href: Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html  
          - text: 3/
            href: Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex03.html  

    right:
      - href: index.qmd
        text: "{{< fa house size=lg >}}"
      - href: about.qmd
        text: "{{< fa at size=lg >}}"

      

format:
  html:
    grid:
      margin-width: 250px
    toc: true
    toc_float: true
    theme: 
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap
    css: styles.css

editor: visual
