---
title: "In-class Exercise 2: Importing Data for Thailand Road Accident Case Study"
title-block-banner: true
date: "02-Sep-24"
date-modified: "last-modified"
toc: true
toc-depth: 4
editor: visual
execute: 
  freeze: true #never re-render during project render
  echo: true #if false, displays charts without codes
  eval: true #if false, displays codes without charts
  warning: false #dont display if there are any warnings
format: 
  html:
    code-fold: false
    code-overflow: scroll
    code-summary: "Show the code"
    code-line-numbers: false
---

::: {.lightbox .light data-latex="light"}

**Reminders**

Check units of measurement in projected coordinates system

:::

# 1 The Packages

```{r}
pacman::p_load(sf, tmap, tidyverse)
```

# 2 Loading the Data


## 2.1 Traffic Accident Data

```{r}
rdacc_sf <- read_csv("data/geospatial/thai_road_accident_2019_2022.csv") %>%
  filter(!is.na(longitude) & longitude != "",
         !is.na(latitude) & latitude !="") %>% 
  st_as_sf(coords = c(
    "longitude", "latitude"),
    crs = 4326) %>% 
  st_transform(crs = 32647)
```

## 2.1 Administrative Boundary

```{r}
adminboundary <- st_read(dsn = "data/geospatial", 
                layer = "geoBoundaries-THA-ADM0")
```

```{r}
par(bg = '#E4D5C9')

plot(adminboundary)
```


## 2.3 Thai Roads

```{r}
roads <- st_read(dsn = "data/geospatial", 
                layer = "hotosm_tha_roads_lines_shp")
```
